### ISSUE TITLE
Interface names and routing

### ISSUE THREAD

**Issue by plomdawg** [Teradata/stacki-ubuntu#2]
Quick background of what I've been trying to do: 
The goal is to be able to plug in any NUC and at the end of the process have a fully functioning desktop that can function on its own (no reliance on the frontend after the initial install). 

Following Phase 2 of Ubuntu on Stacki, I was able to install the Server version of Ubuntu, but struggled a few days with trying to get the Desktop version to install, so I've decided it would be easier to just install Ubuntu Server and "upgrade" it to Desktop with a GUI and a few extra packages. However, I just realized my backend does not have internet access and still needs a bit to be set up

I know Ubuntu on Stacki isn't fully ready yet, but I was wondering how much was supposed to work and isn't before going on to do things by hand

1. Setting the interface to "null" on CentOS nodes update to real names after a successful install, but on Ubuntu it seems to change the interface name to "null" during setup. The interface still works (enough to ping the frontend's IP - dns isn't working but that's another issue I'm figuring out on the frontend)
```
root@nuc1:~# ifconfig
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:14752 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14752 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:1091768 (1.0 MB)  TX bytes:1091768 (1.0 MB)

null      Link encap:Ethernet  HWaddr f4:4d:30:6e:8c:1d  
          inet addr:192.168.30.20  Bcast:192.168.30.255  Mask:255.255.255.0
          inet6 addr: fe80::f64d:30ff:fe6e:8c1d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:24836 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11852 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:36429536 (36.4 MB)  TX bytes:892083 (892.0 KB)
          Interrupt:16 Memory:dc200000-dc220000 

```
2. More important problem is that routes seem to be missing - should I be adding these in on my own or should they be showing up?
```
root@nuc1:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.30.0    0.0.0.0         255.255.255.0   U     0      0        0 null
```

also I was wondering if line 54 from backend/nodes/ubuntu-netcfg.xml was correct:  
in-target /bin/cp /target/etc/network/interfaces.static /target/**etc**/etc/network/interfaces;
```
root@nuc1:~# ls /etc/etc/  
ls: cannot access '/etc/etc/': No such file or directory
```
although this file is here it seems to have made it somehow
```
root@nuc1:~# cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto null
iface null inet static
  address 192.168.30.20
  netmask 255.255.255.0
  gateway 192.168.30.254
  nameservers 192.168.30.254
```
any push in the right direction to where I should start would help, thank you!

**Comment by jlkaiser** [comment]
Next release of stacki-ubuntu should take care of this. Release should be out by the end of the week. There is not support for auto discovery of machines. So you'll have to supply a hosts file to get the interface naming to work. 

Thanks,

Joe

**Comment by plomdawg** [comment]
I'd continue it there, but I haven't yet been accepted to join the stacki google group or invited to the Slack group

I rewrote a "discover-nodes" in bash that generates a hosts.csv file for each node, using NULL as the interface. That seemed to work on CentOS, I guess I'll have to name them myself for Ubuntu. 

Thanks for the update on the release of stacki-ubuntu, sadly this is my last week working at this internship - but I hope to see it before I leave!

**Comment by anooprajendra** [comment]
Hi,

Apologies for the delay in joining the Stacki google group. You've been
approved, and you should be able to post messages there.

**Comment by plomdawg** [comment]
Thanks!
